version: '3.1'

services:

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: testdb

  mvcapp:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    

  